### ISSUE TITLE
Provide a `Tooltip` component to be able to show tooltips on any element on the screen

### ISSUE THREAD

**Issue by MadMed677** [MathAndMagic/ui-common#1]
## Description
Currently in `ui-common` we have no `Tooltip` component which basically is used to show tooltips on any elements on the screen.

There are a few options how it might be done

## 1. Bootstrap style
[Bootstrap tooltips](https://getbootstrap.com/docs/5.3/components/tooltips/)
Bootstrap uses custom `data-bs-*` attributes on DOM nodes to provide a logic on top of any HTML element.

### Example:
```html
<button type="button" class="btn btn-secondary"
        data-bs-toggle="tooltip" data-bs-placement="top"
        data-bs-custom-class="custom-tooltip"
        data-bs-title="This top tooltip is themed via CSS variables.">
  My button with tooltip
</button>
```

`data-bs-title` - the tooltip title
`data-bs-toggle` - is a type (I guess Bootstrap have different options but currently we're focusing on `tooltip` right now)
`data-bs-placement` - where the tooltip should appear

### Pros
- Might be added to any HTML node

### Cons
- Provide simple tooltips only with texts. As I can see there [is an option](https://getbootstrap.com/docs/5.3/components/tooltips/#directions) where we provide a HTML string but it would be parsed as HTML, but there is no IDE highlights or any reactivity because we will place just a string which is not developer friendly, but it will work

## 2. MUI style
[Material UI provide a Tooltip](https://mui.com/material-ui/react-tooltip/) as a separate component which has much more customization than Bootstrap style.

### Example:
```html
<Tooltip
  title={
    <div>
      <p>Hello</p>
      <p>World</p>
    </div>
  }
  placement="top-start"
>
  <Button>top-start</Button>
</Tooltip>
```

### Pros
- As a separate component it might be also used on top of any other components
- Has more flexibility to add new properties to the `Tooltip` component
- It should be easier to manage types because we just have to provide `Tooltip` props and avoid customization of global properties for the any HTML element (like in Bootstrap any HTML element should have `data-bs-*` attributes)

### Cons
Don't see any, but maybe there will be anything

## Suggestion
I'd like to stick to MUI approach because it's more robust and there is a space to add extra properties to `Tooltip` component and be able to improve it and make it more complicated in the future

**Comment by ri-nat** [comment]
MUI style looks more Yew-like, as for me
